### ISSUE TITLE
Installing library rent error

### ISSUE THREAD

**Issue by gdalvarezr** [tryton/tryton-documentation#59]
I was able to start library, but I don't know why with library_rent had problems. 
Can anyone give me a clue ? Thanks in advance
gnuhealth@debian:~/gnuhealth/tryton/server/trytond-4.2.8/bin $ ./trytond-admin -u library_rent -d health2
Traceback (most recent call last):
  File "./trytond-admin", line 21, in <module>
    admin.run(options)
  File "/home/gnuhealth/gnuhealth/tryton/server/trytond-4.2.8/trytond/admin.py", line 53, in run
    pool.init(update=options.update, lang=list(lang))
  File "/home/gnuhealth/gnuhealth/tryton/server/trytond-4.2.8/trytond/pool.py", line 142, in init
    self.start()
  File "/home/gnuhealth/gnuhealth/tryton/server/trytond-4.2.8/trytond/pool.py", line 95, in start
    register_classes()
  File "/home/gnuhealth/gnuhealth/tryton/server/trytond-4.2.8/trytond/modules/__init__.py", line 377, in register_classes
    the_module.register()
  File "/home/gnuhealth/gnuhealth/tryton/server/trytond-4.2.8/trytond/modules/library_rent/__init__.py", line 16, in register
    module='library_rent', type_='model'
  File "/home/gnuhealth/gnuhealth/tryton/server/trytond-4.2.8/trytond/pool.py", line 84, in register
    assert issubclass(cls.__class__, PoolMeta), cls
AssertionError: <class 'trytond.modules.library_rent.library.Book'>

**Comment by pokoli** [comment]
The problem is that the library was developed for tryton 3.2 series, and you are using the 4.2 series. 

Probably the documentation should be updated to be used on a more recent version.

**Comment by gdalvarezr** [comment]
Thanks for the answer Sergi,
I figure it out to work making some changes on the way to use PoolMeta,
this worked for me , took as example GNUhealth
class Party(metaclass=PoolMeta):
    __name__ = 'party.party'

    # Reverse relation for book.renter (reference to all rented books)
    rented_books = fields.One2Many('library.book', 'renter', 'Rented Books')

Regards

**Comment by pokoli** [comment]
@gdalvarezr Just for the record, this change is required only if using python3
